### ISSUE TITLE
Nothing happen when i run this code

### ISSUE THREAD

**Issue by dp2022** [lowbyteproductions/Turning-Pixels-Into-Waves#2]
Could you double check this code? Nothing happen when i try run it. I use "serve" to run this code. All files are served correctly but nothing is displayed. There aren't any error messages in the console, just empty canvas rectangle is visible in the browser.

**Comment by lowbyteproductions** [comment]
This is caused by #1, which has been fixed.
Thanks for letting me know!

**Comment by dp2022** [comment]
That was my fault. I have restrictive browser settings. Works perfectly in Firefox and Chrome. Sorry about that.
